on:
 repository_dispatch:
 workflow_dispatch:
 schedule:
   - cron: "00 18 * * *"
name: Check markdown links
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.4.1
        with:
         args: README.md
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: "[Bot] Broken Links Report"
          content-filepath: ./lychee/out.md
          labels: report
